import type { ReplyRequest } from '../conversations/sendReply.js';

/**
 * GIA's chat through the API (ADR-0052). The answer is generated by AI and only ever shown:
 * nothing in it is run. The chat is not stored; the client sends back its last few turns.
 */

export type GiaScreen =
  'home' | 'gia' | 'conversations' | 'connections' | 'business_profile' | 'department';

export interface GiaTurnView {
  readonly role: 'person' | 'gia';
  readonly text: string;
}

/** Where an answer may take the person in Comercial (C4); the API names only what she read. */
export type GiaLinkView =
  | { readonly kind: 'opportunity'; readonly id: string; readonly label: string }
  | { readonly kind: 'contact'; readonly id: string; readonly label: string | null }
  | { readonly kind: 'conversation'; readonly id: string; readonly label: string | null }
  | { readonly kind: 'follow_up'; readonly id: string; readonly label: string }
  | { readonly kind: 'leads' | 'customers' | 'pipeline' | 'follow_ups' };

/**
 * A follow-up GIA prepared (C5): nothing is scheduled until the person confirms it. `time` is
 * null when the person wrote none, and the app asks for it.
 */
export interface GiaFollowUpProposalView {
  readonly contactId: string;
  readonly contactLabel: string | null;
  readonly opportunityId: string | null;
  readonly opportunityLabel: string | null;
  readonly type: 'follow_up' | 'call' | 'message' | 'review' | 'check_in';
  readonly title: string;
  readonly date: string | null;
  readonly time: string | null;
  readonly timeZone: string;
}

export interface GiaAnswerView {
  readonly answer: string;
  readonly department: string | null;
  readonly screen: GiaScreen | null;
  readonly proposedAction: string | null;
  readonly proposedFacts: number;
  readonly links: readonly GiaLinkView[];
  readonly proposedFollowUp: GiaFollowUpProposalView | null;
  /** The answer carries a finished projection (ADR-0059): by the model or the simple fallback. */
  readonly forecast: 'model' | 'fallback' | null;
  /** What the Forecasting Engine said is missing for a projection, from its own result. */
  readonly forecastGap: GiaForecastGap | null;
}

/**
 * Why no projection was made, as the engine counted it: too little history (or too few periods
 * with activity), a horizon beyond the longest it projects, or company information it needs.
 */
export type GiaForecastGap =
  | {
      readonly kind: 'history' | 'activity';
      readonly have: number;
      readonly need: number;
      readonly unit: 'day' | 'week' | 'month';
    }
  | {
      /** Further ahead than the engine projects: how far was asked and the longest allowed. */
      readonly kind: 'horizon';
      readonly asked: number;
      readonly max: number;
      readonly unit: 'day' | 'week' | 'month';
    }
  | { readonly kind: 'profile' | 'currency' };

export type GiaFailure = 'credits' | 'not_available' | 'rate_limited' | 'failed';

export type GiaResult =
  | { readonly kind: 'answered'; readonly answer: GiaAnswerView }
  | { readonly kind: 'failed'; readonly reason: GiaFailure };

export interface GiaClient {
  ask(input: {
    readonly message: string;
    readonly requestKey: string;
    readonly locale: 'en' | 'es';
    readonly history: readonly GiaTurnView[];
  }): Promise<GiaResult>;
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

function linksOf(raw: unknown): readonly GiaLinkView[] {
  if (!Array.isArray(raw)) return [];
  return raw.flatMap((link): GiaLinkView[] => {
    if (!isRecord(link)) return [];
    const { kind, id, label } = link;
    if (kind === 'leads' || kind === 'customers' || kind === 'pipeline' || kind === 'follow_ups') {
      return [{ kind }];
    }
    if (typeof id !== 'string' || id === '') return [];
    const name = typeof label === 'string' && label !== '' ? label : null;
    if ((kind === 'opportunity' || kind === 'follow_up') && name !== null) {
      return [{ kind, id, label: name }];
    }
    if (kind === 'contact' || kind === 'conversation') return [{ kind, id, label: name }];
    return [];
  });
}

const TYPES = ['follow_up', 'call', 'message', 'review', 'check_in'] as const;
const DAY = /^\d{4}-\d{2}-\d{2}$/;
const CLOCK = /^([01]\d|2[0-3]):[0-5]\d$/;

function proposalOf(raw: unknown): GiaFollowUpProposalView | null {
  if (!isRecord(raw)) return null;
  const { contactId, contactLabel, opportunityId, opportunityLabel, type, title, date, time } = raw;
  const text = (v: unknown) => (typeof v === 'string' && v !== '' ? v : null);
  if (text(contactId) === null || text(title) === null || typeof raw.timeZone !== 'string') {
    return null;
  }
  return {
    contactId: contactId as string,
    contactLabel: text(contactLabel),
    opportunityId: text(opportunityId),
    opportunityLabel: text(opportunityLabel),
    type: (TYPES as readonly unknown[]).includes(type)
      ? (type as (typeof TYPES)[number])
      : 'follow_up',
    title: title as string,
    date: typeof date === 'string' && DAY.test(date) ? date : null,
    time: typeof time === 'string' && CLOCK.test(time) ? time : null,
    timeZone: raw.timeZone,
  };
}

function forecastOf(raw: unknown): GiaAnswerView['forecast'] {
  if (!isRecord(raw) || raw.status !== 'completed') return null;
  return raw.model === 'model' || raw.model === 'fallback' ? raw.model : null;
}

const count = (value: unknown): value is number =>
  typeof value === 'number' && Number.isInteger(value) && value >= 0;

function forecastGapOf(raw: unknown): GiaForecastGap | null {
  if (!isRecord(raw)) return null;
  if (raw.status === 'unavailable') {
    if (raw.reason === 'business_profile_missing') return { kind: 'profile' };
    if (raw.reason === 'currency_missing') return { kind: 'currency' };
    const unit = raw.frequency;
    if (
      raw.reason === 'horizon_out_of_range' &&
      count(raw.horizon) &&
      count(raw.maxHorizon) &&
      (unit === 'day' || unit === 'week' || unit === 'month')
    ) {
      return { kind: 'horizon', asked: raw.horizon, max: raw.maxHorizon, unit };
    }
    return null;
  }
  if (raw.status !== 'insufficient_data' || !count(raw.have) || !count(raw.need)) return null;
  const unit = raw.frequency;
  if (unit !== 'day' && unit !== 'week' && unit !== 'month') return null;
  const kind =
    raw.shortOf === 'active_periods' ? 'activity' : raw.shortOf === 'periods' ? 'history' : null;
  return kind === null ? null : { kind, have: raw.have, need: raw.need, unit };
}

const FAILURES: Readonly<Record<string, GiaFailure>> = {
  ai_credits_insufficient: 'credits',
  ai_not_available: 'not_available',
  ai_policy_denied: 'not_available',
  rate_limited: 'rate_limited',
};

export function createGiaClient(request: ReplyRequest, organizationId: string): GiaClient {
  const path = `/v1/organizations/${encodeURIComponent(organizationId)}/gia/messages`;
  return {
    async ask(input) {
      let response: Response;
      try {
        response = await request(path, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(input),
        });
      } catch {
        return { kind: 'failed', reason: 'failed' };
      }
      const body = (await response.json().catch(() => ({}))) as Record<string, unknown>;
      if (!response.ok) {
        const code = typeof body.error === 'string' ? body.error : '';
        return { kind: 'failed', reason: FAILURES[code] ?? 'failed' };
      }
      if (typeof body.answer !== 'string') return { kind: 'failed', reason: 'failed' };
      return {
        kind: 'answered',
        answer: {
          answer: body.answer,
          department: typeof body.department === 'string' ? body.department : null,
          screen: typeof body.screen === 'string' ? (body.screen as GiaScreen) : null,
          proposedAction: typeof body.proposedAction === 'string' ? body.proposedAction : null,
          proposedFacts: typeof body.proposedFacts === 'number' ? body.proposedFacts : 0,
          links: linksOf(body.links),
          proposedFollowUp: proposalOf(body.proposedFollowUp),
          forecast: forecastOf(body.forecast),
          forecastGap: forecastGapOf(body.forecast),
        },
      };
    },
  };
}
