import { FormattedMessage, useIntl } from '@melonoffice/i18n';
import { Button } from '@melonoffice/ui';
import {
  createContext,
  useCallback,
  useContext,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type FormEvent,
  type ReactNode,
} from 'react';
import { FollowUpForm } from '../followUps/FollowUps.js';
import type { FollowUpView, FollowUpsClient } from '../followUps/followUpsClient.js';
import { navigate } from '../identity/router.js';
import { paths } from '../shell/routes.js';
import { GiaAvatar } from './GiaAvatar.js';
import type {
  GiaAnswerView,
  GiaClient,
  GiaFailure,
  GiaLinkView,
  GiaTurnView,
} from './giaClient.js';

/**
 * GIA's chat in the app (Fase 1c, ADR-0052), shared by the Home's command bar and GIA's
 * Workplace: a message written on the Home continues in the Workplace. The chat lives only in
 * this session; nothing in an answer is run, and every answer says it was generated by AI.
 */

const HISTORY_TURNS = 6;

export type GiaChatEntry =
  | { readonly id: string; readonly role: 'person'; readonly text: string }
  | { readonly id: string; readonly role: 'gia'; readonly answer: GiaAnswerView }
  | { readonly id: string; readonly role: 'error'; readonly reason: GiaFailure };

export interface GiaChat {
  /** False when the role may not talk to GIA: no call is ever made. */
  readonly available: boolean;
  readonly entries: readonly GiaChatEntry[];
  readonly pending: boolean;
  send(text: string): void;
  /** Where a follow-up GIA prepared is confirmed (C5); absent when the role may not schedule. */
  readonly followUps?: FollowUpsClient;
}

const UNAVAILABLE: GiaChat = {
  available: false,
  entries: [],
  pending: false,
  send: () => undefined,
};
const GiaChatContext = createContext<GiaChat>(UNAVAILABLE);

const newKey = () => globalThis.crypto.randomUUID();

export function GiaChatProvider({
  client,
  followUps,
  children,
}: {
  readonly client: GiaClient | undefined;
  /** Follow-ups (C5), for a role that may schedule them: GIA's proposals are confirmed here. */
  readonly followUps?: FollowUpsClient;
  readonly children: ReactNode;
}) {
  const intl = useIntl();
  const locale = intl.locale.toLowerCase().startsWith('es') ? 'es' : 'en';
  const [entries, setEntries] = useState<readonly GiaChatEntry[]>([]);
  const [pending, setPending] = useState(false);

  const send = useCallback(
    (raw: string) => {
      const message = raw.trim();
      if (client === undefined || message === '' || pending) return;
      const history: GiaTurnView[] = entries
        .flatMap((e): GiaTurnView[] =>
          e.role === 'person'
            ? [{ role: 'person', text: e.text }]
            : e.role === 'gia'
              ? [{ role: 'gia', text: e.answer.answer }]
              : [],
        )
        .slice(-HISTORY_TURNS);
      const requestKey = newKey();
      setEntries((current) => [...current, { id: requestKey, role: 'person', text: message }]);
      setPending(true);
      void client
        .ask({ message, requestKey, locale, history })
        .then((result) => {
          setEntries((current) => [
            ...current,
            result.kind === 'answered'
              ? { id: `${requestKey}-a`, role: 'gia', answer: result.answer }
              : { id: `${requestKey}-e`, role: 'error', reason: result.reason },
          ]);
        })
        .finally(() => setPending(false));
    },
    [client, entries, pending, locale],
  );

  const value = useMemo<GiaChat>(
    () =>
      client === undefined
        ? UNAVAILABLE
        : {
            available: true,
            entries,
            pending,
            send,
            ...(followUps === undefined ? {} : { followUps }),
          },
    [client, entries, pending, send, followUps],
  );
  return <GiaChatContext.Provider value={value}>{children}</GiaChatContext.Provider>;
}

export const useGiaChat = () => useContext(GiaChatContext);

const ERRORS: Readonly<Record<GiaFailure, string>> = {
  credits: 'gia.chat.error.credits',
  not_available: 'gia.chat.error.notAvailable',
  rate_limited: 'gia.chat.error.rateLimited',
  failed: 'gia.chat.error.failed',
};

/** How close to the end of the log still counts as reading the latest message, in pixels. */
const AT_END_SLACK = 48;

const isAtEnd = (log: HTMLElement) =>
  log.scrollHeight - log.scrollTop - log.clientHeight <= AT_END_SLACK;

/**
 * Keeps the newest message in view while the person is at the end of the log, on a phone as on a
 * desktop. A person reading earlier messages is never moved: a button offers the newest one
 * instead. What the person sends always brings them back to the end.
 */
function useFollowLatest(entries: readonly GiaChatEntry[], pending: boolean) {
  const log = useRef<HTMLOListElement>(null);
  const following = useRef(true);
  const [behind, setBehind] = useState(false);
  const toEnd = useCallback(() => {
    const element = log.current;
    if (element === null) return;
    element.scrollTop = element.scrollHeight;
    following.current = true;
    setBehind(false);
  }, []);
  const size = entries.length + (pending ? 1 : 0);
  const last = entries.at(-1);
  useLayoutEffect(() => {
    if (size === 0) return;
    if (following.current || last?.role === 'person') toEnd();
    else setBehind(true);
  }, [size, last, toEnd]);
  const onScroll = useCallback(() => {
    const element = log.current;
    if (element === null) return;
    following.current = isAtEnd(element);
    if (following.current) setBehind(false);
  }, []);
  return { log, behind, toEnd, onScroll };
}

/** The conversation and its composer, in GIA's Workplace. */
export function GiaConversation() {
  const intl = useIntl();
  const chat = useGiaChat();
  const [text, setText] = useState('');
  const { log, behind, toEnd, onScroll } = useFollowLatest(chat.entries, chat.pending);
  if (!chat.available) {
    return (
      <p className="panel__empty">
        <FormattedMessage id="gia.chat.unavailable" />
      </p>
    );
  }
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (text.trim() === '' || chat.pending) return;
    chat.send(text);
    setText('');
  };
  return (
    <div className="gia-chat">
      <ol className="gia-chat__log" aria-live="polite" ref={log} onScroll={onScroll}>
        {chat.entries.length === 0 ? (
          <li className="panel__empty">
            <FormattedMessage id="gia.chat.empty" />
          </li>
        ) : null}
        {chat.entries.map((entry) => (
          <li key={entry.id} className={`gia-chat__turn gia-chat__turn--${entry.role}`}>
            {entry.role === 'person' ? (
              <>
                <span className="gia-chat__who">
                  <FormattedMessage id="gia.chat.you" />
                </span>
                <p className="gia-chat__text">{entry.text}</p>
              </>
            ) : entry.role === 'gia' ? (
              <GiaReply answer={entry.answer} />
            ) : (
              <p className="gia-chat__error" role="alert">
                <FormattedMessage id={ERRORS[entry.reason]} />
              </p>
            )}
          </li>
        ))}
        {chat.pending ? (
          <li className="gia-chat__turn gia-chat__turn--gia" role="status">
            <FormattedMessage id="gia.chat.thinking" />
          </li>
        ) : null}
      </ol>
      {behind ? (
        <button type="button" className="gia-chat__latest" onClick={toEnd}>
          <FormattedMessage id="gia.chat.latest" />
        </button>
      ) : null}
      <form className="gia-chat__composer" onSubmit={submit}>
        <textarea
          className="gia-chat__input"
          value={text}
          onChange={(event) => setText(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey) submit(event);
          }}
          placeholder={intl.formatMessage({ id: 'gia.chat.placeholder' })}
          aria-label={intl.formatMessage({ id: 'gia.chat.label' })}
          maxLength={2000}
          rows={2}
        />
        <Button type="submit" disabled={chat.pending}>
          <FormattedMessage id="gia.chat.send" />
        </Button>
      </form>
      <p className="gia-chat__note">
        <FormattedMessage id="gia.chat.cost" /> <FormattedMessage id="gia.chat.notStored" />
      </p>
    </div>
  );
}

/** Where an answer points: a screen of the app, or a department's office. */
function placeOf(
  answer: GiaAnswerView,
  departmentName: string | undefined,
  intl: ReturnType<typeof useIntl>,
): { readonly path: string; readonly label: string; readonly add?: boolean } | undefined {
  switch (answer.screen) {
    case 'home':
      return { path: paths.home(), label: intl.formatMessage({ id: 'nav.home' }) };
    case 'conversations':
      return {
        path: paths.conversations(),
        label: intl.formatMessage({ id: 'nav.communications' }),
      };
    case 'connections':
      return { path: paths.connections(), label: intl.formatMessage({ id: 'nav.connections' }) };
    case 'business_profile':
      // GIA points here when it asks for something the company memory does not have yet.
      return { path: paths.memory(), label: intl.formatMessage({ id: 'nav.memory' }), add: true };
    case 'department':
      return answer.department === null || departmentName === undefined
        ? undefined
        : { path: paths.office(answer.department.replaceAll('_', '-')), label: departmentName };
    default:
      return undefined;
  }
}

/** A record or screen of Comercial an answer names (C4), on the app's own pages. */
function linkOf(
  link: GiaLinkView,
  intl: ReturnType<typeof useIntl>,
): { readonly path: string; readonly label: string } {
  const say = (id: string, values?: Record<string, string>) => intl.formatMessage({ id }, values);
  switch (link.kind) {
    case 'opportunity':
      return {
        path: paths.opportunity(link.id),
        label: say('gia.chat.link.opportunity', { name: link.label }),
      };
    case 'contact':
      return {
        path: paths.customer(link.id),
        label:
          link.label === null
            ? say('gia.chat.link.contactUnnamed')
            : say('gia.chat.link.contact', { name: link.label }),
      };
    case 'conversation':
      return {
        path: paths.conversation(link.id),
        label:
          link.label === null
            ? say('gia.chat.link.conversationUnnamed')
            : say('gia.chat.link.conversation', { name: link.label }),
      };
    case 'leads':
      return { path: paths.contacts('lead'), label: say('gia.chat.link.leads') };
    case 'customers':
      return { path: paths.contacts('customer'), label: say('gia.chat.link.customers') };
    case 'pipeline':
      return { path: paths.pipeline(), label: say('gia.chat.link.pipeline') };
    case 'follow_up':
      return {
        path: paths.followUp(link.id),
        label: say('gia.chat.link.followUp', { name: link.label }),
      };
    case 'follow_ups':
      return { path: paths.followUps(), label: say('gia.chat.link.followUps') };
  }
}

/**
 * A follow-up GIA prepared (C5), for the person to confirm: nothing is scheduled until they do,
 * and the chat says it is scheduled only once the API answered that it is.
 */
function FollowUpProposal({ answer }: { readonly answer: GiaAnswerView }) {
  const chat = useGiaChat();
  const [state, setState] = useState<'open' | 'discarded' | FollowUpView>('open');
  const proposal = answer.proposedFollowUp;
  if (proposal === null) return null;
  if (chat.followUps === undefined) {
    return (
      <p className="gia-chat__meta">
        <FormattedMessage id="gia.chat.followUp.notAllowed" />
      </p>
    );
  }
  if (state === 'discarded') {
    return (
      <p className="gia-chat__meta">
        <FormattedMessage id="gia.chat.followUp.discarded" />
      </p>
    );
  }
  if (state !== 'open') {
    return (
      <p className="gia-chat__meta" role="status">
        <FormattedMessage
          id="gia.chat.followUp.scheduled"
          values={{ title: state.title, date: state.date, time: state.time }}
        />{' '}
        <a
          className="gia-chat__go"
          href={paths.followUp(state.id)}
          onClick={(event) => {
            event.preventDefault();
            navigate(paths.followUp(state.id));
          }}
        >
          <FormattedMessage id="gia.chat.link.followUps" />
        </a>
      </p>
    );
  }
  return (
    <div className="gia-chat__proposal" aria-label="follow-up proposal">
      <p className="gia-chat__meta">
        <FormattedMessage
          id="gia.chat.followUp.prepared"
          values={{
            name: proposal.opportunityLabel ?? proposal.contactLabel ?? '',
          }}
        />
      </p>
      <FollowUpForm
        client={chat.followUps}
        contactId={proposal.contactId}
        {...(proposal.opportunityId === null ? {} : { opportunityId: proposal.opportunityId })}
        initial={{
          type: proposal.type,
          title: proposal.title,
          date: proposal.date,
          time: proposal.time,
        }}
        source="gia"
        onDone={(created) => setState(created ?? 'discarded')}
      />
    </div>
  );
}

function GiaReply({ answer }: { readonly answer: GiaAnswerView }) {
  const intl = useIntl();
  const key = answer.department === null ? undefined : `department.${answer.department}.short`;
  const departmentName =
    key !== undefined && Object.hasOwn(intl.messages, key)
      ? intl.formatMessage({ id: key })
      : undefined;
  const place = placeOf(answer, departmentName, intl);
  return (
    <>
      <span className="gia-chat__who">
        <GiaAvatar size={24} decorative />
        <FormattedMessage id="gia.name" />
      </span>
      <p className="gia-chat__text">{answer.answer}</p>
      {answer.forecast === null ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage
            id={
              answer.forecast === 'model' ? 'gia.chat.forecastModel' : 'gia.chat.forecastFallback'
            }
          />
        </p>
      )}
      {answer.forecastGap === null ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage
            id={`gia.chat.forecastGap.${answer.forecastGap.kind}`}
            values={
              'have' in answer.forecastGap
                ? {
                    have: answer.forecastGap.have,
                    need: answer.forecastGap.need,
                    unit: answer.forecastGap.unit,
                  }
                : 'max' in answer.forecastGap
                  ? {
                      asked: answer.forecastGap.asked,
                      max: answer.forecastGap.max,
                      unit: answer.forecastGap.unit,
                    }
                  : {}
            }
          />
        </p>
      )}
      {departmentName === undefined ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.department" values={{ department: departmentName }} />
        </p>
      )}
      {answer.proposedAction === null ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.suggestion" values={{ action: answer.proposedAction }} />
        </p>
      )}
      {answer.proposedFacts > 0 ? (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.facts" values={{ count: answer.proposedFacts }} />{' '}
          <a
            className="gia-chat__go"
            href={paths.memory()}
            onClick={(event) => {
              event.preventDefault();
              navigate(paths.memory());
            }}
          >
            <FormattedMessage id="gia.chat.reviewFacts" />
          </a>
        </p>
      ) : null}
      {answer.links.length === 0 ? null : (
        <ul className="gia-chat__links" aria-label={intl.formatMessage({ id: 'gia.chat.links' })}>
          {answer.links.map((link, index) => {
            const to = linkOf(link, intl);
            return (
              <li key={`${to.path}:${String(index)}`}>
                <a
                  className="gia-chat__go"
                  href={to.path}
                  onClick={(event) => {
                    event.preventDefault();
                    navigate(to.path);
                  }}
                >
                  {to.label}
                </a>
              </li>
            );
          })}
        </ul>
      )}
      <FollowUpProposal answer={answer} />
      {place === undefined ? null : (
        <a
          className="gia-chat__go"
          href={place.path}
          onClick={(event) => {
            event.preventDefault();
            navigate(place.path);
          }}
        >
          {place.add === true ? (
            <FormattedMessage id="gia.chat.addToMemory" />
          ) : (
            <FormattedMessage id="gia.chat.go" values={{ place: place.label }} />
          )}
        </a>
      )}
      <p className="gia-chat__generated">
        <FormattedMessage id="gia.chat.generated" />
      </p>
    </>
  );
}
