import { FormattedMessage, useIntl } from '@melonoffice/i18n';
import { Button } from '@melonoffice/ui';
import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type FormEvent,
  type ReactNode,
} from 'react';
import { navigate } from '../identity/router.js';
import { paths } from '../shell/routes.js';
import { GiaAvatar } from './GiaAvatar.js';
import type { GiaAnswerView, GiaClient, GiaFailure, GiaTurnView } from './giaClient.js';

/**
 * GIA's chat in the app (Fase 1c, ADR-0052), shared by the Home's command bar and GIA's
 * Workplace: a message written on the Home continues in the Workplace. The chat lives only in
 * this session; nothing in an answer is run, and every answer says it was generated by AI.
 */

const HISTORY_TURNS = 6;

export type GiaChatEntry =
  | { readonly id: string; readonly role: 'person'; readonly text: string }
  | { readonly id: string; readonly role: 'gia'; readonly answer: GiaAnswerView }
  | { readonly id: string; readonly role: 'error'; readonly reason: GiaFailure };

export interface GiaChat {
  /** False when the role may not talk to GIA: no call is ever made. */
  readonly available: boolean;
  readonly entries: readonly GiaChatEntry[];
  readonly pending: boolean;
  send(text: string): void;
}

const UNAVAILABLE: GiaChat = {
  available: false,
  entries: [],
  pending: false,
  send: () => undefined,
};
const GiaChatContext = createContext<GiaChat>(UNAVAILABLE);

const newKey = () => globalThis.crypto.randomUUID();

export function GiaChatProvider({
  client,
  children,
}: {
  readonly client: GiaClient | undefined;
  readonly children: ReactNode;
}) {
  const intl = useIntl();
  const locale = intl.locale.toLowerCase().startsWith('es') ? 'es' : 'en';
  const [entries, setEntries] = useState<readonly GiaChatEntry[]>([]);
  const [pending, setPending] = useState(false);

  const send = useCallback(
    (raw: string) => {
      const message = raw.trim();
      if (client === undefined || message === '' || pending) return;
      const history: GiaTurnView[] = entries
        .flatMap((e): GiaTurnView[] =>
          e.role === 'person'
            ? [{ role: 'person', text: e.text }]
            : e.role === 'gia'
              ? [{ role: 'gia', text: e.answer.answer }]
              : [],
        )
        .slice(-HISTORY_TURNS);
      const requestKey = newKey();
      setEntries((current) => [...current, { id: requestKey, role: 'person', text: message }]);
      setPending(true);
      void client
        .ask({ message, requestKey, locale, history })
        .then((result) => {
          setEntries((current) => [
            ...current,
            result.kind === 'answered'
              ? { id: `${requestKey}-a`, role: 'gia', answer: result.answer }
              : { id: `${requestKey}-e`, role: 'error', reason: result.reason },
          ]);
        })
        .finally(() => setPending(false));
    },
    [client, entries, pending, locale],
  );

  const value = useMemo<GiaChat>(
    () => (client === undefined ? UNAVAILABLE : { available: true, entries, pending, send }),
    [client, entries, pending, send],
  );
  return <GiaChatContext.Provider value={value}>{children}</GiaChatContext.Provider>;
}

export const useGiaChat = () => useContext(GiaChatContext);

const ERRORS: Readonly<Record<GiaFailure, string>> = {
  credits: 'gia.chat.error.credits',
  not_available: 'gia.chat.error.notAvailable',
  rate_limited: 'gia.chat.error.rateLimited',
  failed: 'gia.chat.error.failed',
};

/** The conversation and its composer, in GIA's Workplace. */
export function GiaConversation() {
  const intl = useIntl();
  const chat = useGiaChat();
  const [text, setText] = useState('');
  if (!chat.available) {
    return (
      <p className="panel__empty">
        <FormattedMessage id="gia.chat.unavailable" />
      </p>
    );
  }
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (text.trim() === '' || chat.pending) return;
    chat.send(text);
    setText('');
  };
  return (
    <div className="gia-chat">
      <ol className="gia-chat__log" aria-live="polite">
        {chat.entries.length === 0 ? (
          <li className="panel__empty">
            <FormattedMessage id="gia.chat.empty" />
          </li>
        ) : null}
        {chat.entries.map((entry) => (
          <li key={entry.id} className={`gia-chat__turn gia-chat__turn--${entry.role}`}>
            {entry.role === 'person' ? (
              <>
                <span className="gia-chat__who">
                  <FormattedMessage id="gia.chat.you" />
                </span>
                <p className="gia-chat__text">{entry.text}</p>
              </>
            ) : entry.role === 'gia' ? (
              <GiaReply answer={entry.answer} />
            ) : (
              <p className="gia-chat__error" role="alert">
                <FormattedMessage id={ERRORS[entry.reason]} />
              </p>
            )}
          </li>
        ))}
        {chat.pending ? (
          <li className="gia-chat__turn gia-chat__turn--gia" role="status">
            <FormattedMessage id="gia.chat.thinking" />
          </li>
        ) : null}
      </ol>
      <form className="gia-chat__composer" onSubmit={submit}>
        <textarea
          className="gia-chat__input"
          value={text}
          onChange={(event) => setText(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey) submit(event);
          }}
          placeholder={intl.formatMessage({ id: 'gia.chat.placeholder' })}
          aria-label={intl.formatMessage({ id: 'gia.chat.label' })}
          maxLength={2000}
          rows={2}
        />
        <Button type="submit" disabled={chat.pending}>
          <FormattedMessage id="gia.chat.send" />
        </Button>
      </form>
      <p className="gia-chat__note">
        <FormattedMessage id="gia.chat.cost" /> <FormattedMessage id="gia.chat.notStored" />
      </p>
    </div>
  );
}

/** Where an answer points: a screen of the app, or a department's office. */
function placeOf(
  answer: GiaAnswerView,
  departmentName: string | undefined,
  intl: ReturnType<typeof useIntl>,
): { readonly path: string; readonly label: string } | undefined {
  switch (answer.screen) {
    case 'home':
      return { path: paths.home(), label: intl.formatMessage({ id: 'nav.home' }) };
    case 'conversations':
      return {
        path: paths.conversations(),
        label: intl.formatMessage({ id: 'nav.communications' }),
      };
    case 'connections':
      return { path: paths.connections(), label: intl.formatMessage({ id: 'nav.connections' }) };
    case 'business_profile':
      return { path: paths.business(), label: intl.formatMessage({ id: 'nav.business' }) };
    case 'department':
      return answer.department === null || departmentName === undefined
        ? undefined
        : { path: paths.office(answer.department.replaceAll('_', '-')), label: departmentName };
    default:
      return undefined;
  }
}

function GiaReply({ answer }: { readonly answer: GiaAnswerView }) {
  const intl = useIntl();
  const key = answer.department === null ? undefined : `department.${answer.department}.short`;
  const departmentName =
    key !== undefined && Object.hasOwn(intl.messages, key)
      ? intl.formatMessage({ id: key })
      : undefined;
  const place = placeOf(answer, departmentName, intl);
  return (
    <>
      <span className="gia-chat__who">
        <GiaAvatar size={24} decorative />
        <FormattedMessage id="gia.name" />
      </span>
      <p className="gia-chat__text">{answer.answer}</p>
      {departmentName === undefined ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.department" values={{ department: departmentName }} />
        </p>
      )}
      {answer.proposedAction === null ? null : (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.suggestion" values={{ action: answer.proposedAction }} />
        </p>
      )}
      {answer.proposedFacts > 0 ? (
        <p className="gia-chat__meta">
          <FormattedMessage id="gia.chat.facts" values={{ count: answer.proposedFacts }} />
        </p>
      ) : null}
      {place === undefined ? null : (
        <a
          className="gia-chat__go"
          href={place.path}
          onClick={(event) => {
            event.preventDefault();
            navigate(place.path);
          }}
        >
          <FormattedMessage id="gia.chat.go" values={{ place: place.label }} />
        </a>
      )}
      <p className="gia-chat__generated">
        <FormattedMessage id="gia.chat.generated" />
      </p>
    </>
  );
}
