import type { ReplyRequest } from '../conversations/sendReply.js';

/**
 * GIA's chat through the API (ADR-0052). The answer is generated by AI and only ever shown:
 * nothing in it is run. The chat is not stored; the client sends back its last few turns.
 */

export type GiaScreen =
  'home' | 'gia' | 'conversations' | 'connections' | 'business_profile' | 'department';

export interface GiaTurnView {
  readonly role: 'person' | 'gia';
  readonly text: string;
}

export interface GiaAnswerView {
  readonly answer: string;
  readonly department: string | null;
  readonly screen: GiaScreen | null;
  readonly proposedAction: string | null;
  readonly proposedFacts: number;
}

export type GiaFailure = 'credits' | 'not_available' | 'rate_limited' | 'failed';

export type GiaResult =
  | { readonly kind: 'answered'; readonly answer: GiaAnswerView }
  | { readonly kind: 'failed'; readonly reason: GiaFailure };

export interface GiaClient {
  ask(input: {
    readonly message: string;
    readonly requestKey: string;
    readonly locale: 'en' | 'es';
    readonly history: readonly GiaTurnView[];
  }): Promise<GiaResult>;
}

const FAILURES: Readonly<Record<string, GiaFailure>> = {
  ai_credits_insufficient: 'credits',
  ai_not_available: 'not_available',
  ai_policy_denied: 'not_available',
  rate_limited: 'rate_limited',
};

export function createGiaClient(request: ReplyRequest, organizationId: string): GiaClient {
  const path = `/v1/organizations/${encodeURIComponent(organizationId)}/gia/messages`;
  return {
    async ask(input) {
      let response: Response;
      try {
        response = await request(path, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(input),
        });
      } catch {
        return { kind: 'failed', reason: 'failed' };
      }
      const body = (await response.json().catch(() => ({}))) as Record<string, unknown>;
      if (!response.ok) {
        const code = typeof body.error === 'string' ? body.error : '';
        return { kind: 'failed', reason: FAILURES[code] ?? 'failed' };
      }
      if (typeof body.answer !== 'string') return { kind: 'failed', reason: 'failed' };
      return {
        kind: 'answered',
        answer: {
          answer: body.answer,
          department: typeof body.department === 'string' ? body.department : null,
          screen: typeof body.screen === 'string' ? (body.screen as GiaScreen) : null,
          proposedAction: typeof body.proposedAction === 'string' ? body.proposedAction : null,
          proposedFacts: typeof body.proposedFacts === 'number' ? body.proposedFacts : 0,
        },
      };
    },
  };
}
