import { isGiaError, type GiaErrorCode, type GiaService } from '@melonoffice/gia';
import type { Hono } from 'hono';
import type { ContentfulStatusCode } from 'hono/utils/http-status';
import type { AuthEnv } from './auth.js';
import { withPermission, type AuthorizationDependencies } from './authorization.js';

const STATUS: Record<GiaErrorCode, ContentfulStatusCode> = {
  invalid_request: 400,
  unresolved_tenant: 403,
  requires_user: 403,
  permission_denied: 403,
  organization_inactive: 403,
  rate_limited: 429,
  ai_credits_insufficient: 409,
  ai_policy_denied: 403,
  ai_not_available: 503,
  ai_unavailable: 502,
  ai_timeout: 504,
  ai_invalid_output: 502,
};

const FIELDS = new Set(['message', 'requestKey', 'locale', 'history']);

/**
 * GIA's chat (Fase 1c, ADR-0052): `POST .../gia/messages` with exactly
 * `{ message, requestKey, locale?, history? }`. The organization and the person come from the
 * token and the path. The answer is marked as generated by AI; nothing in it is ever run.
 */
export function registerGiaRoutes(
  app: Hono<AuthEnv>,
  dependencies: AuthorizationDependencies & { readonly gia?: GiaService },
): void {
  const { gia } = dependencies;
  app.post(
    '/v1/organizations/:organizationId/gia/messages',
    withPermission('gia.ask', dependencies, async (c, tenant) => {
      if (gia === undefined) return c.json({ error: 'ai_not_available' }, 503);
      const body: unknown = await c.req.json().catch(() => undefined);
      if (
        typeof body !== 'object' ||
        body === null ||
        Array.isArray(body) ||
        Object.keys(body).some((k) => !FIELDS.has(k))
      ) {
        return c.json({ error: 'invalid_request' }, 400);
      }
      const { message, requestKey, locale, history } = body as Record<string, unknown>;
      try {
        const answer = await gia.ask(tenant, {
          message,
          requestKey,
          ...(locale === undefined ? {} : { locale }),
          ...(history === undefined ? {} : { history }),
        });
        return c.json({ ...answer, generatedBy: 'ai' });
      } catch (error) {
        if (!isGiaError(error)) throw error;
        return c.json(
          { error: error.code, ...(error.field === undefined ? {} : { field: error.field }) },
          STATUS[error.code],
        );
      }
    }),
  );
}
